### ISSUE TITLE
tessellation-with-pixel-texture - IfcPixelTexture pixel binary data alpha position

### ISSUE THREAD

**Issue by Andrej730** [buildingSMART/IFC4.3.x-sample-models#14]
@aothms 

In [IfcPixelTexture example](https://github.com/buildingSMART/IFC4.3.x-sample-models/blob/main/models/tessellated-shape-with-style/tessellation-with-pixel-texture/tessellation-with-pixel-texture.ifc) opacity seems to be positioned at the highest byte - e.g. first pixel is `0FF000000` (`FF` alpha, white color with 100% alpha) but from [IfcPixelTexture specs](https://ifc43-docs.standards.buildingsmart.org/IFC/RELEASE/IFC4x3/HTML/lexical/IfcPixelTexture.htm) it seems that opacity should be at the lowest byte (e.g. `0x0000FF80` - `80` alpha, blue color with 50% alpha).

![image](https://github.com/buildingSMART/IFC4.3.x-sample-models/assets/9417531/39de912c-8833-4754-af63-e6f9b45407e2)

**Comment by aothms** [comment]
You're right as always andrej, not sure how this went unnoticed for over 10y, that surely shows something.

```
import ifcopenshell
pix = f.by_type('IfcPixelTexture')[0][8]
a = numpy.array(list(map(functools.partial(int, base=2), pix))).reshape((256, 256))[::-1,::1]
plt.imshow(a); plt.show()

a = numpy.array(list(map(lambda s: tuple(map(functools.partial(int, base=2), (s[8:16], s[16:24], s[24:32], s[0:8]))), pix))).reshape((256, 256, 4))[::-1,::1]
plt.imshow(a); plt.show()
```

![afbeelding](https://github.com/buildingSMART/IFC4.3.x-sample-models/assets/1096535/f575303a-564f-4de6-999e-17f357ebb76d)

![afbeelding](https://github.com/buildingSMART/IFC4.3.x-sample-models/assets/1096535/d6c37ae8-c633-4723-ab52-935a05513579)

Since I had the code here to do the byte swivelling, I just commited the fix (and fixed a serialization issue in ifcopenshell in the meantime).
